# Generated by Django 5.0 on 2024-01-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesonalinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('Trans', 'Transgender'), ('others', 'others')], default='null', max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('alternativeemail', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('Mobile', models.CharField(max_length=10)),
                ('Street', models.CharField(max_length=100)),
            ],
        ),
    ]
