# Generated by Django 5.0 on 2024-01-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('trans', 'Transgender'), ('others', 'Others')], default='null', max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('alternative_email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('alternative_address', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('mobile', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=100)),
                ('pincodes', models.CharField(max_length=7)),
                ('whatsapp', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Pesonalinfo',
        ),
    ]
