# Generated by Django 5.0 on 2024-01-18 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_personalinfo_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='student',
            new_name='student_name',
        ),
    ]
