# Generated by Django 5.0 on 2024-01-18 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_student_students_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='whatsapp',
        ),
    ]
