# Generated by Django 5.0 on 2024-01-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_students_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='whatsapp',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
