# Generated by Django 5.0 on 2024-01-22 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_students_whatsapp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
