# Generated by Django 5.0 on 2024-01-22 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='college_name',
        ),
    ]
