# Generated by Django 5.0 on 2024-01-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_remove_students_college_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='college_Name',
            field=models.CharField(default='Default_college_name', max_length=100),
        ),
    ]
