# Generated by Django 5.0 on 2024-01-23 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0009_remove_batches_formatted_name'),
        ('students', '0011_alter_students_college_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Enquirysource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='new_app.enquirysource'),
        ),
        migrations.AddField(
            model_name='students',
            name='photo',
            field=models.ImageField(null=True, upload_to='student_photos/'),
        ),
    ]
