# Generated by Django 5.0 on 2024-01-23 05:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0009_remove_batches_formatted_name'),
        ('students', '0012_students_enquirysource_students_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='COURSE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='new_app.course'),
        ),
        migrations.AddField(
            model_name='students',
            name='phone',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='students',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='new_app.qualification'),
        ),
    ]
