# Generated by Django 5.0 on 2024-01-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquirysource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
