# Generated by Django 5.0 on 2024-01-10 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0003_enquirysource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch', models.CharField(max_length=200)),
                ('Trainer_name', models.CharField(max_length=200)),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Followupstatu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Of_The_Follower', models.CharField(max_length=200)),
                ('followup_statu', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=200)),
                ('branch_code', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('pincode', models.IntegerField()),
                ('mobile_number', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=254)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.state')),
            ],
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
