# Generated by Django 5.0 on 2024-01-11 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0005_rename_batch_course_course_remove_course_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Course',
            new_name='course',
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satrt_date', models.DateField()),
                ('Trainer', models.ForeignKey(limit_choices_to={'groups__name': 'Trainer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to=settings.AUTH_USER_MODEL)),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.branches')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.course')),
            ],
        ),
    ]
