# Generated by Django 5.0 on 2024-01-17 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0006_rename_active_course_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.branches')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.course')),
                ('trainer', models.ForeignKey(limit_choices_to={'groups__name': 'Trainer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
