# Generated by Django 5.0 on 2024-01-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0007_batches_delete_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batches',
            name='formatted_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
